Feature/e UI 8669
hmcts/rpx-xui-manage-organisations pull request #1044
Opened 2023-07-31 08:32 UTC by udaydenduluri33

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-8669

### Change description ###

Register Org

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-07-31 12:39 UTC, connorpgpmcelroy requested changes
Minor changes requested

2023-07-31 12:51 UTC, johnbenjamin-hmcts submitted a review, later dismissed

2023-07-31 14:02 UTC, udaydenduluri33 commented on src/register-org/services/register-org.service.ts
> +import { SessionStorageService } from '../../../src/shared/services/session-storage.service';
Removed

2023-07-31 14:02 UTC, udaydenduluri33 commented on src/register-org/register-org.module.ts
> +import { HttpClientModule } from '@angular/common/http';
Fixed the ordering

2023-07-31 14:02 UTC, udaydenduluri33 commented on src/register-org/containers/register/register-org.component.ts
> +import { RegistrationData } from '../../models/registrationdata.model';
Fixed

2023-07-31 14:07 UTC, connorpgpmcelroy submitted a review, later dismissed
LGTM

2023-07-31 14:27 UTC, johnbenjamin-hmcts approved these changes

2023-08-09 08:39 UTC, johnbenjamin-hmcts approved these changes

2023-08-09 08:40 UTC, DavidJayakumar approved these changes

2023-08-10 09:05 UTC, merged