Feature/e UI 8713
hmcts/rpx-xui-manage-organisations pull request #1055
Opened 2023-08-08 13:49 UTC by udaydenduluri33

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-8713

### Change description ###

Regulatory Organisation Type

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2023-08-09 14:15 UTC, johnbenjamin-hmcts submitted a review, later dismissed

2023-08-09 14:22 UTC, connorpgpmcelroy requested changes
Minor changes requested

2023-08-09 14:22 UTC, connorpgpmcelroy commented on api/openRoutes.ts
>  import getappInsightsInstrumentationKey from './monitoring-tools';
minor: import ordering incorrect

2023-08-09 14:22 UTC, connorpgpmcelroy commented on src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
> +                <div class="govuk-hint">Give as much detail as you can on the regulator or profressional body your organisation is registered with.</div>
profressional

2023-08-09 14:23 UTC, DavidJayakumar submitted a review, later dismissed

2023-08-09 14:23 UTC, udaydenduluri33 commented on src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
> +                <div class="govuk-hint">Give as much detail as you can on the regulator or profressional body your organisation is registered with.</div>
Done, Thanks

2023-08-09 14:24 UTC, udaydenduluri33 commented on api/openRoutes.ts
>  import getappInsightsInstrumentationKey from './monitoring-tools';
Changed, thanks

2023-08-09 14:26 UTC, udaydenduluri33 commented on src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.ts
> +import { RegulatoryOrganisationType } from '../../../shared/models/lovRefData.model';
Fixed it, Thanks

2023-08-14 08:59 UTC, connorpgpmcelroy approved these changes
Have approved since issues are minor but still import ordering issues

2023-08-14 08:59 UTC, connorpgpmcelroy commented on src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.ts
> +import { RegulatoryOrganisationType } from '../../../shared/models/lovRefData.model';
I can still see the incorrect ordering?

2023-08-14 08:59 UTC, connorpgpmcelroy commented on src/register-org/register-org.routing.ts
> +import { RegulatoryOrganisationTypeComponent } from './components/regulatory-organisation-type/regulatory-organisation-type.component';
Again, minor, but ./components imports should be together

2023-08-14 09:11 UTC, DavidJayakumar approved these changes

2023-08-14 13:45 UTC, merged