Feature/EUI 8776
hmcts/rpx-xui-manage-organisations pull request #1080
Opened 2023-09-06 13:57 UTC by DavidJayakumar

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-8776

### Change description ###

Add validation for regulatory organisation

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-09-07 14:00 UTC, Daniel-Lam requested changes
@DavidJayakumar - some changes to look at

2023-09-07 14:00 UTC, Daniel-Lam commented on src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
> +                    <br>
@DavidJayakumar - is this `<br>` intentional?

2023-09-08 14:29 UTC, DavidJayakumar commented on src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
> +                    <label class="govuk-label govuk-!-font-weight-bold"
I added it because the font size was larger. It is not a heading for fieldset as well, But still I have changed it

2023-09-08 14:29 UTC, DavidJayakumar commented on src/register-org/models/regulatory-organisation.enum.ts
> +  DUPLICATE_REGULATOR = 'You have entered this registration details more than once'
Changed it after checking with Tommy

2023-09-08 15:08 UTC, Daniel-Lam commented on src/register-org/components/regulatory-organisation-type/regulatory-organisation-type.component.html
> +                    <label class="govuk-label govuk-!-font-weight-bold"
Thanks, @DavidJayakumar - it's a good observation... might be later on, we remove the `<fieldset>` elements altogether if the fields don't really have a common heading

2023-09-08 15:10 UTC, Daniel-Lam approved these changes

2023-09-12 12:49 UTC, merged