Feature/EUI 8786
hmcts/rpx-xui-manage-organisations pull request #1105
Opened 2023-09-21 09:45 UTC by DavidJayakumar

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/EUI-8786

### Change description ###

PostCode validation for UK addresses

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-09-21 13:50 UTC, johnbenjamin-hmcts approved these changes

2023-09-22 08:30 UTC, connorpgpmcelroy approved these changes
LGTM

2023-09-22 10:05 UTC, Daniel-Lam requested changes
@DavidJayakumar - some minor typos but everything else is OK

2023-09-22 10:05 UTC, Daniel-Lam commented on src/custom-validators/postcode.validator.spec.ts
> +  it('validation should return true, when the secod part of postcode is invalid', () => {
@DavidJayakumar - typo `secod`

2023-09-22 10:05 UTC, Daniel-Lam commented on src/custom-validators/postcode.validator.spec.ts
> +  it('validation should be undefined when valid postcode is enterined lowercase', () => {
@DavidJayakumar - typo `enterined`

2023-09-22 10:05 UTC, Daniel-Lam commented on src/custom-validators/postcode.validator.spec.ts
> +  it('validation should be undefined when valid postcode is enterined uppercase with space', () => {
@DavidJayakumar - typo `enterined`

2023-09-22 10:05 UTC, Daniel-Lam commented on src/custom-validators/postcode.validator.spec.ts
> +  it('validation should be undefined when a valid postcode that is not in postcde database is entered', () => {
@DavidJayakumar - typo `postcde`

2023-09-22 10:38 UTC, Daniel-Lam approved these changes

2023-09-26 10:10 UTC, merged