Post Registration Data
hmcts/rpx-xui-manage-organisations pull request #1122
Opened 2023-09-27 10:01 UTC by udaydenduluri33

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-09-29 10:31 UTC, connorpgpmcelroy requested changes
Import ordering issues

2023-09-29 10:31 UTC, connorpgpmcelroy commented on src/register-org/services/register-org.service.ts
> +import { Observable } from 'rxjs';
import ordering - minor issue

2023-09-29 10:31 UTC, connorpgpmcelroy commented on src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
> +import { RegisterOrgService } from '../../services/register-org.service';
ordering

2023-09-29 10:31 UTC, connorpgpmcelroy commented on src/register-org/components/company-house-details/company-house-details.component.spec.ts
> +import { RegisterOrgService } from '../../services/register-org.service';
ordering

2023-09-29 10:31 UTC, connorpgpmcelroy commented on src/register-org/components/check-your-answers/regulator-list/regulator-list.component.spec.ts
> +import { RegisterOrgService } from '../../../services/register-org.service';
ordering

2023-09-29 10:31 UTC, connorpgpmcelroy commented on src/register-org/components/check-your-answers/check-your-answers.component.ts
> +import { HttpErrorResponse } from '@angular/common/http';
ordering

2023-09-29 10:31 UTC, connorpgpmcelroy commented on api/openRoutes.ts
>  import addressRouter from './addresses';
ordering

2023-09-29 10:36 UTC, Daniel-Lam requested changes
@johnbenjamin-hmcts - two minor comments on missing return types

2023-09-29 10:36 UTC, Daniel-Lam commented on src/register-org/components/check-your-answers/check-your-answers.component.ts
> +  public onSubmitData() {
@johnbenjamin-hmcts - missing function return type

2023-09-29 10:36 UTC, Daniel-Lam commented on api/registerOrganisation/index.ts
> +export async function handleRegisterOrgRoute(req: Request, res: Response) {
@johnbenjamin-hmcts - missing function return type

2023-10-02 08:34 UTC, udaydenduluri33 commented on api/registerOrganisation/index.ts
> +export async function handleRegisterOrgRoute(req: Request, res: Response) {
@Daniel-Lam  Done

2023-10-02 08:34 UTC, udaydenduluri33 commented on src/register-org/components/check-your-answers/check-your-answers.component.ts
> +  public onSubmitData() {
@Daniel-Lam  Done

2023-10-02 08:42 UTC, connorpgpmcelroy commented on api/openRoutes.ts
>  import addressRouter from './addresses';
addresses alphabetically before others. However this is openRoutes so actually not necessary

2023-10-02 08:43 UTC, connorpgpmcelroy commented on src/register-org/components/company-house-details/company-house-details.component.spec.ts
> +import { RegisterOrgService } from '../../services/register-org.service';
../../ should come before ./

2023-10-02 08:43 UTC, connorpgpmcelroy commented on src/register-org/components/individual-registered-with-regulator/individual-registered-with-regulator.component.spec.ts
> +import { RegisterOrgService } from '../../services/register-org.service';
../../ should come before ./

2023-10-02 08:45 UTC, Mo-Lala84 approved these changes
approved

2023-10-02 08:53 UTC, connorpgpmcelroy commented on src/register-org/components/check-your-answers/regulator-list/regulator-list.component.spec.ts
> +import { RegisterOrgService } from '../../../services/register-org.service';
../../.. should come before ./ and src mentioned

2023-10-02 08:56 UTC, connorpgpmcelroy approved these changes
LGTM

2023-10-02 09:00 UTC, Daniel-Lam approved these changes

2023-10-03 12:02 UTC, merged