EUI-8921 Register Other Org - Back link issues
hmcts/rpx-xui-manage-organisations pull request #1147
Opened 2023-10-19 13:06 UTC by johnbenjamin-hmcts

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/EUI-8921

### Change description ###
Register other org - click Back link on several pages in the registration journey do not work as expected

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-10-19 20:43 UTC, udaydenduluri33 approved these changes

2023-10-19 20:44 UTC, udaydenduluri33 requested changes
Base branch should be 31.5

2023-10-20 07:31 UTC, johnbenjamin-hmcts commented
> Base branch should be 31.5



> Base branch should be 31.5

@udaydenduluri33 - I changed the base branch to 31.5, the number of files changed increased from 8 to 48.

2023-10-20 08:49 UTC, DavidJayakumar approved these changes

2023-10-24 11:41 UTC, merged