Retrieve secrets via a script
hmcts/rpx-xui-manage-organisations pull request #1205
Opened 2023-11-30 10:33 UTC by shaed-parkar

### Jira link (if applicable)

[GA-63](https://tools.hmcts.net/jira/browse/GA-63)

### Change description ###

Add a setup folder to get the configuration needed to run the web app locally

2023-12-01 09:46 UTC, RiteshHMCTS submitted a review, later dismissed

2024-01-18 16:51 UTC, RiteshHMCTS approved these changes

2024-01-30 09:24 UTC, Josh-HMCTS approved these changes

2024-01-30 09:44 UTC, RiteshHMCTS approved these changes

2024-01-30 10:06 UTC, andywilkinshmcts requested changes
I don't want this code in the repo. I don't see anything that prevents it from being deployed to production, which might result in a file with the secrets being written to the production server, which might theoretically be retrieveal via a browser

2024-05-31 13:11 UTC, closed without merging