GovUK Frontend package update to version 4
hmcts/rpx-xui-manage-organisations pull request #1242
Opened 2024-01-16 13:22 UTC by HYadavHMCTS

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/EXUI-1219

### Change description ###
Installed GovUk-Frontend 4.0.0 package 

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-01-16 14:12 UTC, richardhenryash submitted a review, later dismissed

2024-01-16 14:28 UTC, RiteshHMCTS submitted a review, later dismissed

2024-01-16 17:43 UTC, shaed-parkar reviewed
Though the ticket references v4.0.0, that was simply to point out breaking changes to keep an eye on. Could you target the latest V4, which is 4.7.0, please? Thank you

2024-01-24 09:20 UTC, connorpgpmcelroy submitted a review, later dismissed
LGTM

2024-01-25 07:21 UTC, HYadavHMCTS commented
Updated with latest code review changes. Updated yarn.lock to include common lib ver 2.0.9

2024-01-25 14:14 UTC, HYadavHMCTS commented
updated post review to include common lib ver 2.0.11

2024-01-25 14:22 UTC, andywilkinshmcts submitted a review, later dismissed

2024-01-25 14:23 UTC, RiteshHMCTS submitted a review, later dismissed

2024-01-26 09:53 UTC, HYadavHMCTS commented
Updated yarn audit file after audit failure in build

2024-01-26 09:57 UTC, RiteshHMCTS submitted a review, later dismissed

2024-01-26 10:00 UTC, olusegz07 submitted a review, later dismissed

2024-01-26 11:10 UTC, RiteshHMCTS approved these changes, later dismissed

2024-01-26 11:41 UTC, olusegz07 approved these changes, later dismissed

2024-01-26 12:26 UTC, HYadavHMCTS commented
Added json5 package to dependencies. Babel uses json5 internally. Had a brief chat with @shaed-parkar  around it. Also AKS deploy step in the pipeline fails complaining it couldn't parse 'default.json' config. This should fix that issue

2024-01-26 12:30 UTC, andywilkinshmcts approved these changes, later dismissed

2024-01-26 12:58 UTC, RiteshHMCTS submitted a review, later dismissed

2024-02-15 11:39 UTC, andywilkinshmcts requested changes

2024-02-15 11:39 UTC, andywilkinshmcts commented on package.json
> +    "@hmcts/rpx-xui-common-lib": "2.0.8",
This needs to be updated to latest from master, which is 2.0.10

2026-04-19 19:21 UTC, closed without merging