package.json update - gov-frontend 4.7.0
hmcts/rpx-xui-manage-organisations pull request #1262
Opened 2024-02-02 10:28 UTC by olusegz07

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-02-07 13:29 UTC, connorpgpmcelroy approved these changes
LGTM

2024-02-15 09:12 UTC, HYadavHMCTS submitted a review, later dismissed

2024-02-15 10:08 UTC, andywilkinshmcts requested changes

2024-02-15 10:08 UTC, andywilkinshmcts commented on test_codecept/integration/tests/get_Organisation_User_Details.ts
> +      response.data.users[0].firstName.should.be.eql('Jason');
This is just going to break again. I would change this to search the users array for specific user.

2024-02-15 10:08 UTC, andywilkinshmcts commented on test_codecept/integration/tests/get_Organisation_User_Details.ts
> -      response.data.users[0].idamStatus.should.be.eql('PENDING');
Again - search for a specific user and then check that that user's status is as expected

2024-02-15 10:08 UTC, RiteshHMCTS submitted a review, later dismissed

2024-02-20 12:17 UTC, shaed-parkar commented on package.json
> +    "@hmcts/rpx-xui-common-lib": "2.0.16",
`"govuk-frontend": "3.14.0",` also needs to be upgraded else the project will conflict and I believe use v3 instead

2024-02-21 11:08 UTC, RiteshHMCTS approved these changes

2024-02-21 13:37 UTC, merged