Updating to sync with ccd clean up of case type
hmcts/rpx-xui-manage-organisations pull request #608
Opened 2021-01-14 10:57 UTC by Mo-Lala84

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-3133

### Change description ###
Manage org's Unassigned cases tab fails to load ccd cases with below error for Request URL: https://manage-org.aat.platform.hmcts.net/api/unassignedCaseTypes as a result of ccd cleaning up their definitions in backend.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2021-01-14 10:59 UTC, rayliangatos approved these changes

2021-01-14 11:01 UTC, dharmendrak approved these changes
LGTM

2021-01-14 11:55 UTC, adnanakgun approved these changes

2021-01-14 15:37 UTC, rayliangatos requested changes

2021-01-14 15:37 UTC, rayliangatos commented on config/default.json
> +  "caseTypes": "UNSPECIFIED_CLAIMS,DIVORCE_XUI,MoneyClaimCase,DIVORCE,FinancialRemedyContested,FinancialRemedyMVP2,Asylum,Caveat,GrantOfRepresentation,StandingSearch,WillLodgement,CARE_SUPERVISION_EP
The DIVORCE_XUI needs to be removed as it's also for testing purpose.

2021-01-14 16:08 UTC, rayliangatos approved these changes

2021-01-22 09:57 UTC, dharmendrak approved these changes

2021-03-11 10:38 UTC, closed without merging