EUI-2439-PBA-field
hmcts/rpx-xui-manage-organisations pull request #635
Opened 2021-03-05 17:02 UTC by ishOsw

**Before creating a pull request make sure that:**

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-2439

### Change description ###

Content changes - Show blank PBA field in Organisation tab in MO 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-03-08 09:04 UTC, leepavlouhmcts approved these changes
looks fine

2021-03-08 09:11 UTC, Daniel-Lam requested changes
@ishOsw - one very minor change, otherwise all OK

2021-03-08 09:11 UTC, Daniel-Lam commented on src/organisation/containers/organisation/organisation.component.html
> +        <div><p>Until you’ve added one or more payment by account (PBA) numbers,
@ishOsw - one small change, swap the `’` for a regular `'`... sometimes the "curly" version doesn't render properly on some platforms

2021-03-08 11:10 UTC, Daniel-Lam approved these changes

2021-03-15 09:14 UTC, rayliangatos commented on src/organisation/containers/organisation/organisation.component.html
> +              <p> Contact HMCTS support at <a href="MyHMCTSsupport@justice.gov.uk">MyHMCTSsupport@justice.gov.uk</a> to add a PBA number</p>
it should add the 'mailto' like <a href="mailto:MyHMCTSsupport@justice.gov.uk">

2021-03-16 14:19 UTC, rayliangatos approved these changes

2021-07-08 16:10 UTC, merged