EUI-4697
hmcts/rpx-xui-manage-organisations pull request #925
Opened 2022-09-26 12:53 UTC by maliumer

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EUI-4697

### Change description ###
(Technical Debt)-Unit test Coverage for MO

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-09-26 13:03 UTC, phillip-whitaker-hmcts requested changes

2022-09-26 13:03 UTC, phillip-whitaker-hmcts commented on src/accept-tc/guards/acceptTermsAndCondition.guard.ts
> +  //       }
we shouldn't be committing commented out code

2022-09-26 13:03 UTC, phillip-whitaker-hmcts commented on src/accept-tc/guards/acceptTermsAndCondition.guard.ts
> +  // }
we shouldn't be committing commented out code

2022-09-26 13:03 UTC, phillip-whitaker-hmcts commented on src/accept-tc/containers/accept-tc-wrapper.component.ts
> +  public uidSubscription: Subscription;
why do these need to be public?

2022-09-26 13:03 UTC, phillip-whitaker-hmcts commented on src/app/components/privacy-policy/privacy-policy.component.ts
> +  public subscription: Subscription;
why does this need to be public?

2022-09-27 08:38 UTC, phillip-whitaker-hmcts submitted a review, later dismissed

2022-09-27 08:45 UTC, RiteshHMCTS submitted a review, later dismissed

2022-09-27 08:51 UTC, SivaprakasamSivaprakasam submitted a review, later dismissed

2023-03-06 15:25 UTC, merged